### ISSUE TITLE
Long one word text in explore graph is not contained in the node

### ISSUE THREAD

**Issue by hcaseyal** [hcaseyal/cs147-final-project#84]
<img width="405" alt="screen shot 2017-12-08 at 1 55 26 pm" src="https://user-images.githubusercontent.com/8952658/33786850-91a0279e-dc1f-11e7-9bac-925a7176a79f.png">

I could make the nodes larger

**Comment by yasht2010** [comment]
Yeah. A little larger node would serve the purpose
